### ISSUE TITLE
iOS compatible?

### ISSUE THREAD

**Issue by kondrei** [andrei-rus/music-grid#3]
A testat careva pe iOS? Incarca video in "canvas-output"?
Mie doar un canvas alb si fara nicio eroare.
Imi cere allow la camera dar nu afiseaza nimic nici pe iphone nici pe ipad...

**Comment by andrei-rus** [comment]
Salut,

Da, este compatibil, doar ce am testat pe un mac + Google Chrome.
OS version: 10.15.7
Chrome Version: Version 90.0.4430.212 (Official Build) (x86_64)

Nu pot sa dau un raspuns concret de ce nu ar functiona la tine :)
Daca doresti putem avea un sync sa vedem ce incompatibilities  sunt :)

Merci.
